config/routes.rb
Rails.application.routes.draw do

  root 'home#dermatologyhome'

  resources :patients

  get 'home/dermatologyhome'

  get 'cancelappt/cancelappointment'

  get 'scheduleappt/scheduleappointment'

  get 'physicianhome/physicianhome'

  get 'physicianappt/physicianappointment'

  get 'officework/officeworker'

  get 'officework/edit'

  get 'adminhome/administrator'

  get 'patienthome/home'

  get 'appointments/officeworker'

  get 'appointments/officeworkeredit'

  get 'appointments/cancelappointment'

  resources :invoices

  resources :appointments

  resources :diagnostic_codes

  resources :physicians

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic_code
  has_one :invoice

  validates_uniqueness_of :appointment_date, scope: :physician

end

app/models/diagnostic_code.rb
class DiagnosticCode < ActiveRecord::Base
  has_many :appointments
  has_many :invoices

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic_code
  has_one :appointment
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :appointments
  has_many :patients, :through => :appointments
  has_many :invoices
end

app/controllers/diagnostic_codes_controller.rb
class DiagnosticCodesController < ApplicationController
  before_action :set_diagnostic_code, only: [:show, :edit, :update, :destroy]

  # GET /diagnostic_codes
  # GET /diagnostic_codes.json
  def index
    @diagnostic_codes = DiagnosticCode.page(params[:page]).per(10)
  end

  # GET /diagnostic_codes/1
  # GET /diagnostic_codes/1.json
  def show
  end

  # GET /diagnostic_codes/new
  def new
    @diagnostic_code = DiagnosticCode.new
  end

  # GET /diagnostic_codes/1/edit
  def edit
  end

  # POST /diagnostic_codes
  # POST /diagnostic_codes.json
  def create
    @diagnostic_code = DiagnosticCode.new(diagnostic_code_params)

    respond_to do |format|
      if @diagnostic_code.save
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully created.' }
        format.json { render :show, status: :created, location: @diagnostic_code }
      else
        format.html { render :new }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diagnostic_codes/1
  # PATCH/PUT /diagnostic_codes/1.json
  def update
    respond_to do |format|
      if @diagnostic_code.update(diagnostic_code_params)
        format.html { redirect_to @diagnostic_code, notice: 'Diagnostic code was successfully updated.' }
        format.json { render :show, status: :ok, location: @diagnostic_code }
      else
        format.html { render :edit }
        format.json { render json: @diagnostic_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diagnostic_codes/1
  # DELETE /diagnostic_codes/1.json
  def destroy
    @diagnostic_code.destroy
    respond_to do |format|
      format.html { redirect_to diagnostic_codes_url, notice: 'Diagnostic code was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diagnostic_code
      @diagnostic_code = DiagnosticCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diagnostic_code_params
      params.require(:diagnostic_code).permit(:Code_Num, :Code_Description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:appointment_date, :patient_id, :physician_id, :diagnostic_code_id, :appointment_cost)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patienthome_home_path, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name)
    end
end

app/helpers/adminhome_helper.rb
module AdminhomeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/cancelappt_helper.rb
module CancelapptHelper
end

app/helpers/diagnostic_codes_helper.rb
module DiagnosticCodesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/patienthome_helper.rb
module PatienthomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicianappt_helper.rb
module PhysicianapptHelper
end

app/helpers/physicianhome_helper.rb
module PhysicianhomeHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/scheduleappt_helper.rb
module ScheduleapptHelper
end

app/views/diagnostic_codes/_form.html.erb
<%= form_for(@diagnostic_code) do |f| %>
  <% if @diagnostic_code.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diagnostic_code.errors.count, "error") %> prohibited this diagnostic_code from being saved:</h2>

      <ul>
      <% @diagnostic_code.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Code_Num %><br>
    <%= f.text_field :Code_Num %>
  </div>
  <div class="field">
    <%= f.label :Code_Description %><br>
    <%= f.text_area :Code_Description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diagnostic_codes/edit.html.erb
<h1>Editing Diagnostic Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @diagnostic_code %> |
<%= link_to 'Back', diagnostic_codes_path %>

app/views/diagnostic_codes/index.html.erb
<div id="header">
  <h1>North Houston Dermatology</h1>
</div>
<br>
<div class="breadcrumb">
  <%= link_to "Home", home_dermatologyhome_path %> <span class="divider">/</span>
  <%= link_to "System Admin Home", adminhome_administrator_path %> <span class="divider">/</span>
  Change Diagnostic Code
</div>
<br>
<p id="notice"><%= notice %></p>

<h1>Listing Diagnostic Codes</h1>



<table>
  <thead>
    <tr>
      <th>Code num</th>
      <th>Code description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diagnostic_codes.each do |diagnostic_code| %>
      <tr>
        <td><%= diagnostic_code.codenum %></td>
        <td><%= diagnostic_code.codedescription %></td>
        <td><%= link_to 'Show', diagnostic_code %></td>
        <td><%= link_to 'Edit', edit_diagnostic_code_path(diagnostic_code) %></td>
        <td><%= link_to 'Destroy', diagnostic_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= paginate @diagnostic_codes %>
<br>
<%= link_to 'New Diagnostic code', new_diagnostic_code_path %>

app/views/diagnostic_codes/new.html.erb
<h1>New Diagnostic Code</h1>

<%= render 'form' %>

<%= link_to 'Back', diagnostic_codes_path %>

app/views/diagnostic_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code num:</strong>
  <%= @diagnostic_code.Code_Num %>
</p>

<p>
  <strong>Code description:</strong>
  <%= @diagnostic_code.Code_Description %>
</p>

<%= link_to 'Edit', edit_diagnostic_code_path(@diagnostic_code) %> |
<%= link_to 'Back', diagnostic_codes_path %>